<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selected</name>
   <tag></tag>
   <elementGuidId>25a4a2e7-039e-4b34-9bbf-0c3f581ca174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='selectedButton']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedSecondary' and @type = 'button' and @id = 'selectedButton' and (text() = 'Selected' or . = 'Selected')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1deac78-7a02-45ee-a53f-e579c3b3f27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedSecondary</value>
      <webElementGuid>b1830b74-ace0-4dbc-ba78-f0d0a414489c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3415b2b9-498e-46e2-9254-ccfbb240d5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>107c07b2-d8d3-4065-96be-13faf8fbeadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedButton</value>
      <webElementGuid>afe2488f-546c-44b1-a337-574eae100430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selected</value>
      <webElementGuid>407c72d6-f4a2-4224-b4a6-83b549de2124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedButton&quot;)</value>
      <webElementGuid>294ce26a-ec81-4553-b091-82c931318ee2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='selectedButton']</value>
      <webElementGuid>9eb88a1b-8aa3-4d03-903d-a4fa236daf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='assignmentManagementTableContainer']/div[2]/div/span/button</value>
      <webElementGuid>10ffd76b-d304-4c5f-82a8-f2231b9f2224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm suggestions'])[1]/following::button[1]</value>
      <webElementGuid>434f07c9-378d-41dd-bf60-c6577fd86657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select users'])[1]/following::button[2]</value>
      <webElementGuid>3dabc359-d62f-478d-b1eb-634ec7313a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtered'])[1]/preceding::button[1]</value>
      <webElementGuid>dd384e27-c293-477a-a855-7a02d70d13f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>71708587-ff83-409f-8841-efe8b11476ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'selectedButton' and (text() = 'Selected' or . = 'Selected')]</value>
      <webElementGuid>63fdee9f-50f0-463a-9278-cf160cb90817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
