<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonmenuButton</name>
   <tag></tag>
   <elementGuidId>c3caae80-e5ba-4d17-a14b-db7495f6f1ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ffc090a-8d92-4b66-ad3f-7b2fde106453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root jss152 MuiIconButton-colorInherit</value>
      <webElementGuid>02648664-090f-40ea-914c-a048666fc5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f63d2ab-a358-4f49-b119-119c28021b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>200abd73-a3c9-40a0-aea0-cc3305166a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuButton</value>
      <webElementGuid>d5ae2f6d-d616-4784-9ea5-38fbdf348f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>e56cfd98-7846-458c-b674-10b43a6ca65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuButton&quot;)</value>
      <webElementGuid>cd42db0c-d497-4390-ab2e-f04a6c1293b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menuButton']</value>
      <webElementGuid>fcba84d4-5f62-4b9e-a4e7-a09607232bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header-content']/div/header/div/button</value>
      <webElementGuid>6903c62a-a975-412b-9c18-809f4139911f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>55fc4a1f-32c5-4e23-8c45-0d965b3225dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menuButton']</value>
      <webElementGuid>8298262e-b673-4583-9c47-f506ecca4f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
