<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonsearchResultsButton</name>
   <tag></tag>
   <elementGuidId>ff14beaf-fbb6-456b-aff2-b548f8de6564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchResultsButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchResultsButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e722e93-eb6b-406d-8514-4e6cda38b22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>eccb6088-88e8-4ad2-8fd5-acdc596cf974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f2f17fe6-1f1b-48eb-b0fe-56648447b86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6962e0f-b101-47e0-a3f6-65ab65dba07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchResultsButton</value>
      <webElementGuid>47a1b021-3b3a-4e1c-a812-40e965c37f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>362ad5de-2bfa-4f8b-b9f8-a7f0f1598b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResultsButton&quot;)</value>
      <webElementGuid>8953ead2-afcc-4f09-bf2f-e537d80ff01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchResultsButton']</value>
      <webElementGuid>dc9e0d6f-684a-4ead-b6f4-0e259b5795c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assignmentManagementDashboard']/div/div/div/div/header/div/div/button</value>
      <webElementGuid>3da6a78d-2a00-4884-90ea-37e4f3144dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/header/div/div/button</value>
      <webElementGuid>4d8c0359-619d-4aac-a8a4-fb365f9605e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'searchResultsButton']</value>
      <webElementGuid>06e90ee8-0cb6-4b5f-a84c-0d1b5e90a4d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
