<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>125a89cb-04e0-4fcf-8278-d3ec60fe7165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-visitCaseStates > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-visitCaseStates']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c5c0408-d9a2-402f-9293-9d28a879a03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4ccc0a8-5728-4f19-b367-d98ed2ffe2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-visitCaseStates&quot;)/div[1]</value>
      <webElementGuid>4d8bc84a-f61f-46a1-b346-866115b502f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-visitCaseStates']/div</value>
      <webElementGuid>ec78363c-55d8-4abc-9a6b-ce44cb5668f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>1401303d-4e69-4898-8ddc-c36abee2f9c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
