<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>426c2024-3128-4a6a-bcb6-33db69d08540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-component-select-visitCaseStates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-component-select-visitCaseStates']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input' and @role = 'button' and @id = 'mui-component-select-visitCaseStates' and (text() = '​' or . = '​')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9e4e60e-609d-4388-b797-c495bff4c4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input</value>
      <webElementGuid>8f7f5568-346d-4641-bf5a-fdad241150b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>013c3849-cb52-4aef-ae5e-f3b4153ac005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14d7ca45-e737-48d4-8693-e1894e78eef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>20b0fa55-e71d-4365-bdf9-e51d7306812d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-component-select-visitCaseStates</value>
      <webElementGuid>89a8d532-373f-4392-9976-5050351f9de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-component-select-visitCaseStates</value>
      <webElementGuid>4d84d8d0-ff08-4de3-add3-ce817eb53e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>71d29e37-ae0e-4e2f-a494-53b15d76fbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-component-select-visitCaseStates&quot;)</value>
      <webElementGuid>9dedf9eb-69c5-4a06-8854-4118deb96b47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-component-select-visitCaseStates']</value>
      <webElementGuid>02af59fb-002f-408b-bcad-e6b8d28ef881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterContainer']/div/div[2]/div/div/div/div/ul/li[2]/div/div/div/div/div</value>
      <webElementGuid>c2c68731-99df-44e2-a69f-32d377a73083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case state'])[1]/following::div[4]</value>
      <webElementGuid>257fc968-9d4c-44b9-a432-3c0f5ee72c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[5]</value>
      <webElementGuid>e378f754-e47e-4608-acef-3772207be9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case ID'])[1]/preceding::div[1]</value>
      <webElementGuid>e37465b0-cf70-40d1-b1d3-589a0a2b159d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/div</value>
      <webElementGuid>7f2fee59-82e7-476f-a899-e94f30c336d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-component-select-visitCaseStates' and (text() = '​' or . = '​')]</value>
      <webElementGuid>42530896-4d7f-41ea-adbf-09403529e5e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
