<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDToken1</name>
   <tag></tag>
   <elementGuidId>ca54cb29-a318-487e-a9fd-c6f0ce95a37c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IDToken1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IDToken1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0713a12-00b0-47b2-ac91-e00b52c2cd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>faadc0cb-e8ff-49d6-8a3f-eef92d7b3903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IDToken1</value>
      <webElementGuid>cd9d58f3-45cd-4b36-9a9c-12fc628b4bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e2c0cfc6-4706-452b-877c-5c194629ce6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IDToken1</value>
      <webElementGuid>f79c7458-4fa1-4919-905c-515e1378ae52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91123368-3501-412c-b600-a29220cbf1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4a43a47e-c0d3-4e44-a094-232f7770fcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IDToken1&quot;)</value>
      <webElementGuid>610ef289-549c-4406-a068-0e4a6e631002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IDToken1']</value>
      <webElementGuid>e51d95b8-6cbe-4dd9-bc4b-ee9a03febaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div/input</value>
      <webElementGuid>5e23ff01-50f2-475e-b48b-97ef92b52b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b3f04d5f-fb7f-4129-9faa-95d1fb60f9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IDToken1' and @name = 'IDToken1' and @type = 'text']</value>
      <webElementGuid>a7111f9e-5ea5-4af2-b18e-76668b276575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
