<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jss429</name>
   <tag></tag>
   <elementGuidId>4828841a-ff9a-41e3-a889-2331fae809af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiButtonBase-root.MuiIconButton-root.jss332.MuiRadio-root.MuiRadio-colorSecondary.jss333.Mui-checked.MuiIconButton-colorSecondary > span.MuiIconButton-label > input[name=&quot;geolocationFilterType&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='geolocationFilterType'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'jss335' and @name = 'geolocationFilterType' and @type = 'radio' and @value = 'dailyRoute']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c377236-71ac-4ac4-ae44-42e9b9fb075e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss335</value>
      <webElementGuid>2df5db3b-d0aa-4177-a1bf-215afa6f2997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>06e43f5d-d0e8-4c0c-a330-4df6cb5a4275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>051e9d2b-7d17-4c71-ad4d-97f3dd985aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>dailyRoute</value>
      <webElementGuid>6c6ca395-3be1-4930-a877-94680cd86de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geolocationFilterSelector&quot;)/div[@class=&quot;MuiPaper-root MuiExpansionPanel-root MuiExpansionPanel-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiButtonBase-root MuiExpansionPanelSummary-root jss308&quot;]/div[@class=&quot;MuiExpansionPanelSummary-content&quot;]/div[1]/div[@class=&quot;MuiFormGroup-root&quot;]/label[@class=&quot;MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss332 MuiRadio-root MuiRadio-colorSecondary jss333 Mui-checked MuiIconButton-colorSecondary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss335&quot;]</value>
      <webElementGuid>64824e0f-6d81-4f7a-b43e-cccbaed20303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>geolocationFilterType</value>
      <webElementGuid>39e633e5-7379-419b-b358-4164ba1b9bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='geolocationFilterType'])[2]</value>
      <webElementGuid>3bb5088a-037c-4e34-9bf5-fb94ec2b40d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationFilterSelector']/div/div/div/div/div/label[2]/span/span/input</value>
      <webElementGuid>a0f82a92-b4bd-41bd-8b30-191755915575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/span/input</value>
      <webElementGuid>7ca909dd-2487-4c16-b5d7-bc2e60e31ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'geolocationFilterType' and @type = 'radio']</value>
      <webElementGuid>42b9faa7-b9b9-45f0-8c5f-5aaa3c7abb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='geolocationFilterType']</value>
      <webElementGuid>65d5b808-3467-46d4-8a46-c31648c7f036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationFilterSelector']/div/div/div/div/div/label/span/span/input</value>
      <webElementGuid>0a7f45c6-fec1-4dc9-8102-5dbe8f3b3179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b7f4b442-753e-4c99-a64e-a48423df5a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='23']</value>
      <webElementGuid>73a5413f-fe0b-4352-b7cd-3cb93bdf8f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='assignmentManagementTableContainer']/div[3]/table/tbody/tr/td/span/span/input</value>
      <webElementGuid>459acbf9-02f3-43d0-83e4-b3156f5315c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/span/input</value>
      <webElementGuid>f55df7d9-8944-4b9a-935f-ff9daa7930b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>5b447d7a-300e-4f40-9cea-1d74516230fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='529']</value>
      <webElementGuid>60c33311-6a0d-4976-a335-f8ee6a1256fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='assignmentManagementTableContainer']/div[3]/table/tbody/tr[2]/td/span/span/input</value>
      <webElementGuid>d4ab7cc5-ac9b-4676-b1fe-4e2061c29e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span/span/input</value>
      <webElementGuid>d2970e10-266f-4960-826e-7a363ed1943c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='524']</value>
      <webElementGuid>a763853e-ff91-42c5-a341-bdc631936219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
