<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonmenuButton</name>
   <tag></tag>
   <elementGuidId>c7847921-5172-478d-9351-8be34bf4c819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59df431a-0342-4990-8ef9-31d4436d9ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root jss152 MuiIconButton-colorInherit</value>
      <webElementGuid>ab3b3957-b689-4d00-8640-d059c994bcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f689ce35-f39a-4e15-b1f9-5267dab3f72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f53cc19-816c-45de-a801-9fc47066990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuButton</value>
      <webElementGuid>7dfbdb26-53c9-453d-8263-d8d7e3a6e60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>45d88c96-087b-49c4-8e73-c3aa7108cc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuButton&quot;)</value>
      <webElementGuid>ad6cd36e-a5fa-4fdb-8478-51c682b3cbfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menuButton']</value>
      <webElementGuid>faa7aca5-6ef2-4d62-b492-ce0ccbfea0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header-content']/div/header/div/button</value>
      <webElementGuid>b10bafe3-7f26-40e8-98f9-1016a32882eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7aa4e3b1-be2c-4cdf-aa84-8d99905e5a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menuButton']</value>
      <webElementGuid>f221d2ce-69f0-4913-84cf-06558e520426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
