<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttontoggleFilterMenuButton</name>
   <tag></tag>
   <elementGuidId>8296a2ae-4497-42e4-b206-ef6c8c408b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleFilterMenuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='toggleFilterMenuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daf12258-5fd8-4031-8d89-d0140348bb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>887c6173-399c-4c10-bae5-63947c0e3697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>75528865-1b32-4083-9897-f58ac79fd262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>713f833a-8904-4c1b-98a2-907213d35328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleFilterMenuButton</value>
      <webElementGuid>1cbb69a8-b044-4c30-a573-86bbe9cc1bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>opened</value>
      <webElementGuid>4c256ac4-4c17-4b78-9de1-feafdee6c53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle filter menu</value>
      <webElementGuid>6f76563e-0124-4343-9741-0f616dbc5218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-80044</value>
      <webElementGuid>e4e5facd-ba08-4738-b6e9-014a8a516a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggleFilterMenuButton&quot;)</value>
      <webElementGuid>edd10235-16e3-4a0a-887f-ebddffc51fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='toggleFilterMenuButton']</value>
      <webElementGuid>2c33fbd2-81bf-41a7-8cf9-4a8a4164680f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationTracking']/div/div/div/div/header/div/button</value>
      <webElementGuid>a47431b9-f2af-4228-a9ec-6b39386b9988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/header/div/button</value>
      <webElementGuid>21844aa6-24b7-4d9c-b752-b243ac995820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'toggleFilterMenuButton']</value>
      <webElementGuid>4042ddfb-7069-4179-b176-2891bb19f5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
