<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonsearchResultsButton</name>
   <tag></tag>
   <elementGuidId>0e9b41ed-8a96-4b6f-a9f2-bb2964c20d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchResultsButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchResultsButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d238581-59ab-4606-ae89-e5b64a5e48f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>f4f0cf89-54d6-4f0d-b402-751f77ce8859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2f83bdf-5295-488f-95b2-66c7cbc3f1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e5e7382f-1c34-4655-9c48-fecdeec75718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchResultsButton</value>
      <webElementGuid>5efc4e24-338c-411e-8a0c-2e76dd4aa9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d4a8b19e-d98f-4fed-9c0f-8f9511626a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResultsButton&quot;)</value>
      <webElementGuid>89495dd1-cddd-4bd4-ac77-0a9a9d5ce67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchResultsButton']</value>
      <webElementGuid>55de1661-da27-434c-8f02-2148a98a6da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationTracking']/div/div/div/div/header/div/div/button</value>
      <webElementGuid>0f2c487d-ebae-4c9d-a20e-0f34a8ba97db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/header/div/div/button</value>
      <webElementGuid>6ec5f29f-86ae-4473-9e32-d62e44552701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'searchResultsButton']</value>
      <webElementGuid>04794602-9284-4e0f-be19-3111a9adc6af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
