<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonclearFilterButton</name>
   <tag></tag>
   <elementGuidId>d2315216-c06b-4dd9-a5c2-f70f7a452528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clearFilterButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='clearFilterButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70fe193d-d031-41cc-bcfe-4cf0f6366a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>9131db48-4b9b-4dd4-856e-795b203216fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32374996-e5ef-4e3c-ad8d-892d2b3a5106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f48693f-ed90-4d05-97b4-cdd676a40ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clearFilterButton</value>
      <webElementGuid>4f0c06d7-1f6f-4e38-891f-38fbda17799c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Clear visit case filter</value>
      <webElementGuid>6f09b021-dda7-44b5-9c81-f876ebb55c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-18422</value>
      <webElementGuid>369c2991-82e0-4fe0-b1b1-97a13e987dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clearFilterButton&quot;)</value>
      <webElementGuid>d6fec0db-eb4f-486b-9698-a49587b17779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='clearFilterButton']</value>
      <webElementGuid>711355bd-d6d2-454c-a296-ffb13823d0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationTracking']/div/div/div/div/header/div/button[2]</value>
      <webElementGuid>c0d0134d-5787-437a-972d-1dd3833f3424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>d3333224-3e28-4d57-ac7b-4a97b0e00d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'clearFilterButton']</value>
      <webElementGuid>53c0d07c-c31b-485b-bd48-372300048757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
