<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select location</name>
   <tag></tag>
   <elementGuidId>4394a505-d957-4272-bdd9-676b4d017f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='locationButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>631d4368-be9a-4ee8-a0ac-93f21d8fc60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItem-root MuiListItem-gutters MuiListItem-button MuiListItem-secondaryAction</value>
      <webElementGuid>e3f19906-a4fc-408a-892e-bb244b490318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6e89ffe-b4f9-4faa-9305-2ba3e975530d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b05b1af8-a68c-4a4e-8976-0f9df6f6323c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>10050553-9717-4d90-83c0-5717619f7ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationButton</value>
      <webElementGuid>27ddb4dc-685d-40f7-84bf-d0fa33f23100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select location</value>
      <webElementGuid>2885b123-3cd6-4431-9347-decce98d187f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationButton&quot;)</value>
      <webElementGuid>e4aad41e-f142-458b-aade-5fac3224999b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='locationButton']</value>
      <webElementGuid>cbb2e7d1-149f-44d9-9937-1c97b7fb13a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationTracking']/div/div[2]/div/div/aside/div/div[2]/ul/li/div/div/ul/li/div</value>
      <webElementGuid>daf09cd7-af32-4f08-9683-bfbc88daf32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/ul/li/div</value>
      <webElementGuid>16c2e0fb-7f94-4689-bf05-f00c74bdb906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'locationButton' and (text() = 'Select location' or . = 'Select location')]</value>
      <webElementGuid>a14fd03c-a0d9-4858-bc2b-e9d3d7b434cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
