<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RegionRegion</name>
   <tag></tag>
   <elementGuidId>fb598ce7-abe0-4a7d-9ab8-e5742afa26ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Region</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Region']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>404988e5-6744-457a-932e-616085f701b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Region</value>
      <webElementGuid>22b64fd3-108e-4954-86d8-cfdfe849b2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Region​Region</value>
      <webElementGuid>4662a47c-d2a3-4267-8fdd-44604be5fb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Region&quot;)</value>
      <webElementGuid>64e866eb-81e1-4c7a-9b57-13202ca80e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Region']</value>
      <webElementGuid>8dddd198-c2e5-4e6c-b1e8-8bd343bbd830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select location'])[2]/following::div[5]</value>
      <webElementGuid>d7b4ae82-fd23-4184-94bd-723747f9ee4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'Region', '&quot;', ')')])[1]/following::div[11]</value>
      <webElementGuid>748b2180-8d46-49bc-94d7-7f6f7d353dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>d1d5fc37-c0ea-4c59-9c0f-51e2175389d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Region' and (text() = 'Region​Region' or . = 'Region​Region')]</value>
      <webElementGuid>49735dd5-f039-427d-bab7-9fb18ad3ae4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
