<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_muf_tester</name>
   <tag></tag>
   <elementGuidId>3a44e543-a413-4f6f-b40f-900964631e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downshift-1-item-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='downshift-1-item-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59efd929-f38b-49b3-95f5-2b97da8193d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItem-root MuiMenuItem-root Mui-selected MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-selected</value>
      <webElementGuid>c2f1165e-afdb-4aaa-98ea-94ec581e7273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ca8b1400-40fa-4c17-b22e-be670bc505b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>fa41f49a-b75f-4571-8617-76988a2d1423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>67d1b17c-597d-4d40-a8bd-90765faf6d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-1-item-0</value>
      <webElementGuid>c816776c-1166-4576-801c-15961e8e91a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>muf_tester</value>
      <webElementGuid>2a646c13-28c4-4607-876e-2b0123714e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-1-item-0&quot;)</value>
      <webElementGuid>33287958-ec4f-4ac5-88ee-26090b3b56ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='downshift-1-item-0']</value>
      <webElementGuid>42bc2905-2522-4f8d-b0f1-13d04a536b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationTracking']/div/div[2]/div/div/aside/div/div[2]/ul/li/div/div/div/div[2]/div/div</value>
      <webElementGuid>ac4b209f-670b-423d-8a3b-29ee8c437a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visitor'])[1]/following::div[7]</value>
      <webElementGuid>ae97bfbe-5924-4d72-916e-4d6ed29cac21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Route'])[1]/following::div[13]</value>
      <webElementGuid>21d3de43-ec0d-45be-9e02-e7e0a40b8287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::div[1]</value>
      <webElementGuid>845f3a02-0fcb-4aeb-8d0d-579c9edba6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::div[1]</value>
      <webElementGuid>5721c3e9-b355-42aa-9208-b7be8f108f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='muf_tester']/parent::*</value>
      <webElementGuid>eb0fd4b5-dbf7-45a0-b8fb-4bee8bafbbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div[2]/div/div</value>
      <webElementGuid>f0df077a-f42b-4fb9-988d-ae9067e2f336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'downshift-1-item-0' and (text() = 'muf_tester' or . = 'muf_tester')]</value>
      <webElementGuid>5d66d1c5-e0c7-4818-8c0b-855a90d4c4f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
