<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Route)_geolocationFilterType_Route</name>
   <tag></tag>
   <elementGuidId>0a50b516-57b7-4331-ba2f-640b2a87de81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiButtonBase-root.MuiIconButton-root.jss332.MuiRadio-root.MuiRadio-colorSecondary.jss333.Mui-checked.MuiIconButton-colorSecondary > span.MuiIconButton-label > input[name=&quot;geolocationFilterType&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='geolocationFilterType'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56bc071a-1723-44a3-b3b8-cffcb3614ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss335</value>
      <webElementGuid>5cbc7acb-7c38-41bb-a1d7-e476b59a83c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>geolocationFilterType</value>
      <webElementGuid>571602a4-ae4a-4cd3-8bf3-c9d8c03a7daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1daaa427-9e5c-4fae-b576-b220c77fe00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>dailyRoute</value>
      <webElementGuid>582218df-71f4-4478-92b5-459a0e0be151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geolocationFilterSelector&quot;)/div[@class=&quot;MuiPaper-root MuiExpansionPanel-root MuiExpansionPanel-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiButtonBase-root MuiExpansionPanelSummary-root jss308&quot;]/div[@class=&quot;MuiExpansionPanelSummary-content&quot;]/div[1]/div[@class=&quot;MuiFormGroup-root&quot;]/label[@class=&quot;MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss332 MuiRadio-root MuiRadio-colorSecondary jss333 Mui-checked MuiIconButton-colorSecondary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss335&quot;]</value>
      <webElementGuid>fb738968-9a97-4060-96e5-820e4d9b901e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='geolocationFilterType'])[2]</value>
      <webElementGuid>99371be2-530f-4899-ba5a-04ef0750688a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationFilterSelector']/div/div/div/div/div/label[2]/span/span/input</value>
      <webElementGuid>ada5fecc-7ae1-452d-bddb-d5a6375e8f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/span/input</value>
      <webElementGuid>e31b271f-13ec-45a0-b4d9-75acdb9569e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'geolocationFilterType' and @type = 'radio']</value>
      <webElementGuid>ec32670a-f8a1-4bde-8a67-3bd0c4b619de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
