<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_geolocationFilterType</name>
   <tag></tag>
   <elementGuidId>ceb3cf66-7d6f-4822-ad0a-c2f30880b720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;geolocationFilterType&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='geolocationFilterType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1479d4b7-d16b-4608-a2b3-e6039712a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss335</value>
      <webElementGuid>b068c39b-2761-406b-be7d-c897427a7f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>geolocationFilterType</value>
      <webElementGuid>c75de29f-61e5-48bf-9275-d2b28407160a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0c53859c-cb15-4d49-a0e9-0d8c7bb35a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>teamPosition</value>
      <webElementGuid>c16faba1-1d4e-44f9-b777-e49e4b1392a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geolocationFilterSelector&quot;)/div[@class=&quot;MuiPaper-root MuiExpansionPanel-root MuiExpansionPanel-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiButtonBase-root MuiExpansionPanelSummary-root jss308&quot;]/div[@class=&quot;MuiExpansionPanelSummary-content&quot;]/div[1]/div[@class=&quot;MuiFormGroup-root&quot;]/label[@class=&quot;MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss332 MuiRadio-root MuiRadio-colorSecondary jss333 Mui-checked MuiIconButton-colorSecondary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss335&quot;]</value>
      <webElementGuid>5fcfdfb4-bdb6-4129-b1eb-50a41c7f8885</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='geolocationFilterType']</value>
      <webElementGuid>d0721f2e-f9ef-4d8c-a337-c3e5072b113b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='geolocationFilterSelector']/div/div/div/div/div/label/span/span/input</value>
      <webElementGuid>e258dd56-5bdd-4bdb-8365-beebb7bcbedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e93c1d53-d726-4fd1-b53d-86cc6b7fda5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'geolocationFilterType' and @type = 'radio']</value>
      <webElementGuid>f8b433b1-ba88-4cbe-96de-8db7b839d390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
