<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_enroll</name>
   <tag></tag>
   <elementGuidId>0b6e3ab4-7b5e-4808-abac-9650615ab13e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='userManagementTableContainer']/div/table/tbody/tr/td[8]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.MuiButton-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e6dc3b0-4bff-47e4-ab34-5bde4da7b607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-label</value>
      <webElementGuid>0cec1a13-a74f-40e9-919f-b21a42351d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>enroll</value>
      <webElementGuid>152a1176-10a3-445d-830b-866ad2938905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userManagementTableContainer&quot;)/div[@class=&quot;MuiPaper-root jss605 MuiPaper-elevation1 MuiPaper-rounded&quot;]/table[@class=&quot;MuiTable-root&quot;]/tbody[@class=&quot;MuiTableBody-root&quot;]/tr[@class=&quot;MuiTableRow-root&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained jss635 MuiButton-containedSizeSmall MuiButton-sizeSmall&quot;]/span[@class=&quot;MuiButton-label&quot;]</value>
      <webElementGuid>e4c9096c-ce28-4c1d-aec9-37bc45d5bf72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='userManagementTableContainer']/div/table/tbody/tr/td[8]/button/span</value>
      <webElementGuid>c09ba5f0-656f-4467-bd08-3a50ec1bca0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/button/span</value>
      <webElementGuid>cd354726-3898-481c-8570-52486e64beaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'enroll' or . = 'enroll')]</value>
      <webElementGuid>2e7c6148-b562-4822-8151-96fe103099f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
