<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Capture object_menuButton</name>
   <tag></tag>
   <elementGuidId>0fdeadb2-0c6a-4052-8643-1bfb3cf9b59b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a89cedc-1842-4e97-ba9b-f71e35c6eaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root jss152 MuiIconButton-colorInherit</value>
      <webElementGuid>5e679cf4-ed83-4b3b-a9a6-7bf4a40877df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>05b716f3-3829-4991-a9ec-8a5b1968be72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e07a6f8c-b09d-4de6-bb75-b4a5fa5a70ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuButton</value>
      <webElementGuid>d5a2b492-9ac4-4835-8bb0-9ab987acf6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>4f1ab63e-d430-4868-be4c-7a4d37c068be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuButton&quot;)</value>
      <webElementGuid>16f6cd64-81df-4178-8cdf-3634ef5e65cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menuButton']</value>
      <webElementGuid>1ed31b00-e90d-4aee-8a84-8a0ac5a70946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header-content']/div/header/div/button</value>
      <webElementGuid>05ebc22b-9e73-4511-a5a7-ef925efb8ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[2]</value>
      <webElementGuid>585ed78c-52cb-4399-9b11-26628b128e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[2]</value>
      <webElementGuid>6649bf9e-ca8c-4337-8e54-0750472a880f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>317019f4-48e3-42cf-a1d3-d83ef57fb19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menuButton']</value>
      <webElementGuid>90515a48-529d-41af-8dd8-f4896225fc27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
