<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDToken1</name>
   <tag></tag>
   <elementGuidId>a11ea1c1-0b8e-43d6-afc6-deafbc6d9540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IDToken1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IDToken1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'IDToken1' and @name = 'IDToken1' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61f47ffb-72ae-436e-9bb8-1d9a1fbf4a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b6faed3a-9c8e-42f9-a370-96f0c5bf3648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IDToken1</value>
      <webElementGuid>29f4a6d6-5be8-49c9-9873-520ad6550d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>881510aa-f519-473f-aa39-4a7286fe0095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IDToken1</value>
      <webElementGuid>6df6a468-34f2-46db-8133-565b60e422e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5da8d215-ecf7-4338-8807-9478b74a78f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a277d6a-699d-46ef-a719-503a52dc9af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IDToken1&quot;)</value>
      <webElementGuid>6cef6c04-4688-43b3-928c-47e59a651689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IDToken1']</value>
      <webElementGuid>46fe967f-ac04-4147-8474-8c03b6306411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div/input</value>
      <webElementGuid>8ef6330b-95e2-453d-a084-34a371532d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>54b34ecc-c43d-47b8-826a-2be6e747e6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IDToken1' and @name = 'IDToken1' and @type = 'text']</value>
      <webElementGuid>69c575b3-3a1a-4835-b0e9-8aa1f9bc20c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
