<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonmenuButton</name>
   <tag></tag>
   <elementGuidId>6aa3b282-6b3e-4723-91b7-942c6f928d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f327932a-03bf-425a-b723-658ecfffb344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root jss152 MuiIconButton-colorInherit</value>
      <webElementGuid>1be114d6-acc4-425e-9a82-3600ca7592ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11294533-e88a-43d1-aec4-dca02674d206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5598adee-6276-484e-91f8-208e0f14030e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuButton</value>
      <webElementGuid>5764dbb4-1e72-457f-bc05-2885bc5ab57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>930ed28c-b83e-46ac-8b45-bc0502a8364b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuButton&quot;)</value>
      <webElementGuid>8cbca89d-c8f8-4911-881b-b2ecec443305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menuButton']</value>
      <webElementGuid>9b84a612-2b8b-4299-91f6-fd2b66294ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header-content']/div/header/div/button</value>
      <webElementGuid>18af6728-86df-41f7-a02f-32ee697a6e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit overview'])[1]/preceding::button[1]</value>
      <webElementGuid>a3d60c35-0ce6-49f4-bee9-b15f25ffa3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case'])[1]/preceding::button[10]</value>
      <webElementGuid>e61f6cad-d113-4a2e-9156-10e677a381c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>be2b5d91-051f-4afa-8ec8-fe390d5399a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menuButton']</value>
      <webElementGuid>b8b36dc1-fc57-4c57-bdf5-ebfee594c1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User management'])[1]/preceding::button[1]</value>
      <webElementGuid>7dc3cbc6-3a82-45ea-b8af-f1636a6f1f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internal'])[1]/preceding::button[7]</value>
      <webElementGuid>1edf9c58-c95d-43f8-878f-47c8858cd3e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
