<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Visit overview_searchResultsButton</name>
   <tag></tag>
   <elementGuidId>5d0b6472-07f7-4479-8419-aeafa05d741a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchResultsButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchResultsButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52508d34-67cf-4a43-a4a5-2a06193d2379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>380be8b1-739e-4a0d-b014-70d67cd40568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6eca3631-8537-4328-afe7-76f8939792db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd103cdd-a5e9-4ee2-9143-24e8208c021d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchResultsButton</value>
      <webElementGuid>8d348c81-f241-45fe-ae81-dc549d132a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>bb576f8e-4247-47c7-a34d-e0e9714eb75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResultsButton&quot;)</value>
      <webElementGuid>2d3e6167-7514-4ba4-adfa-6c17d108100c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchResultsButton']</value>
      <webElementGuid>6d31a1c2-aed1-41b2-8d76-8ba204a8a342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalVisitCaseDashboard']/div/div/div/div/header/div/div/button</value>
      <webElementGuid>d775c284-3055-4262-8bb1-e67c04b330e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit overview'])[1]/following::button[5]</value>
      <webElementGuid>3805f3bd-b8e1-4dc2-a0aa-333aae9591cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case'])[1]/preceding::button[5]</value>
      <webElementGuid>bfc0059c-d33f-4d66-823f-cfce5a40af5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case type'])[1]/preceding::button[5]</value>
      <webElementGuid>8b22e234-bbef-40c4-ae80-1d46b299ae29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/header/div/div/button</value>
      <webElementGuid>f9eb3a6a-ee89-4942-ae25-c956c99443aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'searchResultsButton']</value>
      <webElementGuid>0d656c01-dad6-45f4-9d31-3f6daae132a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
