<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ (1)</name>
   <tag></tag>
   <elementGuidId>d3150168-674c-4224-a118-fb33318929c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-component-select-visitCaseStates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-component-select-visitCaseStates']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>67b109bd-876b-415f-96b6-70bb25be19d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input</value>
      <webElementGuid>5cdc3eb7-2606-43da-97b2-91d5d5d82652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3007caeb-6cf6-4550-89f8-dd386d985565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48b38e00-efa7-451c-b356-e63a049060ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>b40052dd-b9b8-4cbb-953f-9acb40937732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-component-select-visitCaseStates</value>
      <webElementGuid>bca3d077-cb04-46ec-93b6-d26af2384493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-component-select-visitCaseStates</value>
      <webElementGuid>30965050-5ca4-4a43-b269-fdc56050abb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>c35384f9-b42e-47a7-bfae-55c91824dd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-component-select-visitCaseStates&quot;)</value>
      <webElementGuid>f7a57551-1540-4987-9c3d-bd318c0975a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-component-select-visitCaseStates']</value>
      <webElementGuid>4ca09205-a06e-45a3-8e61-f5e3565897db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterContainer']/div/div[2]/div/div/div/div/ul/li[2]/div/div/div/div/div</value>
      <webElementGuid>ae156722-0bcb-42a0-a883-61a452281262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case state'])[1]/following::div[4]</value>
      <webElementGuid>92e08d49-2b34-4615-95c0-635c19421604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[5]</value>
      <webElementGuid>675a4235-c9b8-4a8f-a275-2be92da9d406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case ID'])[1]/preceding::div[1]</value>
      <webElementGuid>c13960fe-e6bd-4552-ad02-3dbfefbdaafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/div</value>
      <webElementGuid>b8692f31-06b0-4f07-9cde-1f9d93a69eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-component-select-visitCaseStates' and (text() = '​' or . = '​')]</value>
      <webElementGuid>7764cc1c-3ca5-4244-8ceb-1b65c6bfa17c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
