<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>5614752b-5a02-44b1-89fd-3b6b50240945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-component-select-visitCaseStates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-component-select-visitCaseStates']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mui-component-select-visitCaseStates' and (text() = '​' or . = '​')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2a53da1-91a0-4a57-a0d8-835323e77aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input</value>
      <webElementGuid>d687ea15-e12c-4b09-9945-bbf4452175b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>044093b1-f9c7-4fa3-bc96-5ce0c2e43c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e47b534e-1814-402f-a1fe-d21221276360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>5ddca3b5-74f4-4059-95f6-251792ecd439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-component-select-visitCaseStates</value>
      <webElementGuid>c6b40b17-7b1f-49cb-8d44-a5470cfd4f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-component-select-visitCaseStates</value>
      <webElementGuid>46fe1da4-5ec4-4225-899a-e73e9c7766ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>a5d2ea48-cd25-471a-a942-4e1fb4227023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-component-select-visitCaseStates&quot;)</value>
      <webElementGuid>6c0d0de8-9fbc-4500-b92c-34bfdf0747b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-component-select-visitCaseStates']</value>
      <webElementGuid>b6e7d591-2435-463e-9b3c-c4494dcf65db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterContainer']/div/div[2]/div/div/div/div/ul/li[2]/div/div/div/div/div</value>
      <webElementGuid>f921d2f8-f9c8-4a88-9828-8783b76987d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case state'])[1]/following::div[4]</value>
      <webElementGuid>7477390b-cd47-4efa-9b47-f074e8db7ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[5]</value>
      <webElementGuid>d5d6c7cf-9467-47cb-8c05-37a52d9ccb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit case ID'])[1]/preceding::div[1]</value>
      <webElementGuid>2a5a252f-dd37-451a-bad5-490fc3ee3056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/div</value>
      <webElementGuid>bda55217-72a3-4d5e-9733-0a1ea62d6228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-component-select-visitCaseStates' and (text() = '​' or . = '​')]</value>
      <webElementGuid>04833382-ce51-43e7-b486-954e5e840483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
